FROM alpine:3.19.1

# Install required dependencies
RUN apk add git openjdk11 apache-ant make gcc g++ musl-dev python3 py3-pip libcurl cmake libxml2 openssl build-base gnuplot texlive R  R-dev R-doc linux-headers libxml2-dev fontconfig-dev harfbuzz-dev fribidi-dev freetype-dev libpng-dev tiff-dev libjpeg
RUN R -e "options(repos = c(CRAN = 'http://cran.rstudio.com/')); install.packages('tidyverse', dependencies=TRUE, Ncpus = 6);"

# Copy required files
ADD ./analyzer /analyzer

# Setup mona
WORKDIR /analyzer
RUN git clone https://github.com/seecurity/mona-timing-report.git
WORKDIR /analyzer/mona-timing-report
RUN git checkout 4c74fb7e629b4d057b2d5d4accdb120d920774b7 \
    && git apply /analyzer/patches/mona.patch \
    && ant

# Setup dudect
WORKDIR /analyzer
RUN git clone https://github.com/oreparaz/dudect.git
WORKDIR /analyzer/dudect
RUN git checkout 66190a8e4e878352b566a20ccb8cef69bb06a915 \
    && git apply /analyzer/patches/dudect-real.patch \
    && make

# Setup tlsfuzzer
WORKDIR /analyzer
RUN git clone https://github.com/tlsfuzzer/tlsfuzzer.git
WORKDIR /analyzer/tlsfuzzer
RUN git checkout c8651f4944925a7d75fa785a5de23f9b4791afc5 \
    && git apply /analyzer/patches/tlsfuzzer.patch \
    && python3 -m venv /venv \
    && . /venv/bin/activate \
    && pip install six ecdsa numpy scipy pandas matplotlib tlslite-ng==0.8.0-beta1 \
    && make install \
    && deactivate

# Setup analyzer
WORKDIR /analyzer/scripts
ENTRYPOINT ["python3", "analyzeRealMeasurements.py"]
